### PR TITLE
A little more information in the READMEs

### PR DESCRIPTION
**Pull request by dogoepp**
Hi,

I thought that we might add a few words in the readmes. It's not much so feel free to discard if not interested.

Also, we might add the license, the authors and contributors and the projects that openly use this tool. What do you think ?

### CODE REVIEW

**Comment by AndriyPt** [comment]
@dogoepp currently @toliver is on vacations. He will be back in a week and will review your pull request.

**Comment by toliver** [comment]
@dogoepp Thanks for improving the READMEs. I'm happy to merge.

**Comment by toliver** [comment]
About the license and authors, currently this is in https://github.com/shadow-robot/optoforce/blob/indigo-devel/optoforce/package.xml#L8.

This is the usual place for this info in ROS. Would you suggest some other format?

**Comment by dogoepp** [comment]
You're right. I had forgotten that we put this information in the package.xml file usually for ROS. Putting this information in the README would make it a duplicate then. It's fine like that.

Thanks

**Pull request merged**
