### PR TITLE
Finish #23

### PR DESCRIPTION
**Pull request by dogoepp**
This commit changes frame header-size association. It was a fix for #23 but was not integrated in time.

### CODE REVIEW

**Comment by dg-shadow** [comment]
Can you tell me what issue this is resolving? The device we have works fine and gives no errors with the driver as is...

**Comment by dogoepp** [comment]
Two days ago you wrote 

> Hi. I may be doing something stupid, but when I test this with a 4-channel device, I get
> [ERROR] [WallTime: 1480962669.037774] optoforce: Bad checksum in frame: (170, 7, 8, 28, 240, 197, 0, 0, 0, 1, 0, 2, 0, 21, 255, 237, 0, 19, 0, 4, 0, 3)
> ad infintum :/ Any ideas as to why?

I made a fix and asked you to checkout a specific branch to check it. I assume you did so and it worked. However, this fix had not been integrated within the pull request #23. I expect that if you checkout `shadow-robot:indigo-devel` the issue mentioned above will come again. Hence this new pull request that implements the missing fix.

Or did I misunderstand something ?

**Comment by dg-shadow** [comment]
Right, I was the one doing the misunderstanding ;) With you now, thanks.

**Comment by dogoepp** [comment]
Thanks a lot for accepting #23 and this pull request :-)

**Comment by dg-shadow** [comment]
No probs, thanks for your contribution :)

**Pull request merged**
