### PR TITLE
Decode all 3 types of sensor

### LINKED ISSUE #12: Add single channel 3axis to driver
Adapt the driver to decode a single channel 3 axis sensor (DAC box with a single sensor).

### PR DESCRIPTION
**Pull request by toliver**
**DO NOT MERGE YET**
Wait until this can be tested at least with the multi-channel 3 axis sensors.

The single-channel sensors available at the moment have an older FW and  protocol version (see branch  F_older_single_channel).

Fixes #12

### CODE REVIEW

**Comment by toliver** [comment]
I wouldn't recommend to merge branch F_older_single_channel to the trunk, as it makes the code a bit more messy and we are unlikely to want support for older FW versions in the future.

**Comment by ugocupcic** [comment]
@toliver can you notify me when it's been tested? I'm happy to merge it after that.

**Comment by toliver** [comment]
Yes. But it can be a while until we have sensors available.

**Comment by toliver** [comment]
Tested with the multichannel 3 axis. We can merge it.

**Pull request merged**
